#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := theremin

EXTRA_COMPONENT_DIRS += ../../ESP32AudioLibrary
EXTRA_COMPONENT_DIRS += ../../AFSCoreTwoTwoLibrary
include $(IDF_PATH)/make/project.mk

